#!/bin/bash

source ~/.cache/wal/colors.sh

#terminate already running bar instances
killall -q dunst

dunst --frame_color $color3 --separator_color $color3 -lb $background  -lf $foreground -lfr $color2 -nb $background -nf $foreground -nfr $color2 -cb $background -cf $foreground -cfr $color2 & 
#dunst &




