#!/bin/env python

import os

FZF_ARGS = str("--height=10% --border --preview-window=0")

def tty_termite_and(x):
    os.system("echo 'ANDROID , TTY e TERMITE\n\nAplicando o tema'")
    os.system("/home/pablo951_br/Downloads/scripts/wall_cores_android '%s'"%(x))
    os.system("echo 'ANDROID , TTY e TERMITE\n\nSenha de Root para refazer a initramfs e afins'")
    os.system('/home/pablo951_br/Downloads/scripts/cores_tty_termite.sh')
    os.system('sudo mkinitcpio -p linux')
    os.system("echo 'ANDROID , TTY e TERMITE\n\nTema aplicado!'")

def image():
    os.system("echo 'Aperter ENTER para selecionar a imagem desejada e continuar'") 
    path0 = str(os.popen('find /home/pablo951_br/.imagens -type d | fzf %s ' %(FZF_ARGS)).read().rstrip())
    path = str(os.popen("find '%s' | fzf %s" %(path0,FZF_ARGS)).read().rstrip())
    return path


def wallpaper(x):
    path = x
    os.system("nitrogen --head=0 --set-scaled '%s' ; nitrogen --head=1 --set-scaled '%s'" %(path,path))
    os.system("echo '%s Wallpaper Changed'"%(path))
    os.system("printf '[xin_0]\nfile='%s'\nmode=0\nbgcolor=#222222\n\n[xin_1]\nfile='%s'\nmode=0\nbgcolor=#222222' > /home/pablo951_br/.config/nitrogen/bg-saved.cfg "%(path,path))


def backend():
    os.system("echo 'BACKEND:\n\nEscolha o backend do pywal'")
    backend = str(os.popen(("printf 'wal\nschemer2\ncolorthief\nhaishoku\ncolorz' | fzf %s" %(FZF_ARGS))).read().rstrip())
    return backend


def interativo():
    path = image()
    back = backend()
    os.system("wal -n -i '%s' --backend %s"%(path,back))
    os.system("echo '%s Colorscheme changed.'" %(path))
    os.system("echo '[wallaper]\n%s\n\n[tema]\nwal -g -i %s --backend %s' > ~/Downloads/Outros/ultimo-tema-wal.txt" %(path,path,backend))
    print("Deseja selecionar a imagem como Wallpaper?")
    wall = str(os.popen("printf 'no\nyes' | fzf %s " %(FZF_ARGS)).read().rstrip())
    print() 
    if(wall=='yes'):
        wallpaper(path) 
    print()
    print("Deseja aplicar o tema no TTY,TERMITE E ANDROID?*\n\n*obs:O android deverá estar conectado via ADB(cabo ou wireless)")
    andro = str(os.popen("printf 'no\nyes' | fzf %s" %(FZF_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(path)


def clip():
    print()
    clip = str(input("Cole o caminho da imagem,se estiver na TTY use o tmux(CTRL-A + SPACO + Y ; CTRL-A + V)\n\n>>> ").rstrip())
    back = backend()
    os.system("wal -n -i '%s' --backend %s" %(clip,back))
    print("Deseja selecionar a imagem como Wallpaper?")
    wall = str(os.popen("printf 'no\nyes' | fzf %s " %(FZF_ARGS)).read().rstrip())
    print() 
    if(wall=='yes'):
        wallpaper(clip) 
    print()
    print("Deseja aplicar o tema no TTY,TERMITE E ANDROID?*\n\n*obs:O android deverá estar conectado via ADB(cabo ou wireless)")
    andro = str(os.popen("printf 'no\nyes' | fzf %s" %(FZF_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(clip)


def tema():
    os.system("echo 'TEMA:\n\nEscolha um tema pré-definido pelo pywal'")
    tema = str(os.popen("cat /home/pablo951_br/Downloads/Outros/pywall-best-themes.txt | fzf %s" %(FZF_ARGS)).read().rstrip())
    os.system('wal --theme %s'%(tema))
    print()
    os.system(" echo 'TEMA:\n\nTema %s aplicado'" %(tema))
    print()
    os.system("echo 'wal --theme %s' > ~/Downloads/Outros/ultimo-tema-wal.txt" %(tema)) 
    wall = str(os.popen("printf 'no\nyes' | fzf %s" %(FZF_ARGS)).read().rstrip())
    if(wall=='yes'):
        wallp = image()
        wallpaper(wallp) 
    print()
    print("Deseja aplicar o tema no TTY,TERMITE E ANDROID?*\n\n*obs:O android deverá estar conectado via ADB(cabo ou wireless)")
    andro = str(os.popen("printf 'no\nyes' | fzf %s" %(FZF_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(wallp)

#***COMEÇO***
os.system("echo 'CHCOLOR:\n\nScript para setar as cores do pywal no sistema, termite e tty' ")
print()

#pergunta se será :  imagem modo interativo(sxiv) , imagem via clipboard ou tema pre-feito do pywwal
os.system("echo 'MODUS-OPERANDI\n\nINTERATIVO:Abre uma janela do fzf onde a imagem será selecionada\n\nINTERATIVO:A imagem será selecionada da clipboard\n\nTEMA:Será selecionado um tema pré-feito do pywal*\n\n*temas preferidos no arquivo Downloads/Outros/pywall-best-themes.txt'") 

while(True):
    ask0 =  str(os.popen("printf 'interativo\nclipboard\ntema' | fzf %s" %(FZF_ARGS)).read().rstrip())
    print(ask0)
    if (ask0 == 'tema'):
        tema()
        break
    elif (ask0 == 'clipboard'):
        clip()
        break
    elif (ask0 == 'interativo'):
        interativo()
        break
    else:
        quit()
