#!/usr/bin/env python

import os

#local das musicas baixadas
pasta ='/home/pablo951_br/musicas/'
#arquivo contendo os links 
arquivo ='/home/pablo951_br/musicas.txt'

def prepare():
    os.system('mkdir %s > /dev/null'%(pasta))
    links = open('%s'%(arquivo))
    return links

def download(links):
    for link in links:
        print()
        print("Script para baixar multiplas musicas")
        print()
        if link.startswith(' '):continue
        link = link.rstrip()
        os.system("youtube-dl --prefer-ffmpeg --ignore-config --geo-bypass --extract-audio --audio-format mp3 --audio-quality 0 -o '"+pasta+"/%(title)s.%(ext)s' " + "'" + link + "' | tee '"+pasta+"log.txt'")
        os.system("clear")

download(prepare())

