#!/bin/sh

OPTION="$(printf "Fullscreen\nCurrent Window\nChoose Area" | dmenu -p "What type of screenshot?: ")"

case "$OPTION" in
	"Fullscreen")
		scrot /home/pablo/pictures/Fullscreen-"$(date +%Y-%m-%d_%H:%M:%S)".png
		;;
	"Current Window")
		scrot -u /home/pablo/pictures/Window-"$(date +%Y-%m-%d_%H:%M:%S)".png
		;;
	"Choose Area")
		scrot -s /home/pablo/pictures/Area-"$(date +%Y-%m-%d_%H:%M:%S)".png
		;;
	"*")
		exit 1
		;;
esac
