#!/bin/sh


source ~/.cache/wal/colors.sh

DMENU_ARGS="-nf #ffffff -nb #222222 -sb $color1 -sf $color15 -fn envypn-9"

pkill -f /dev/video || ask=$(printf "320x240\n640x480" | dmenu $DMENU_ARGS -i -p "Select recording style:")
 
if [ "$ask" = "320x240" ] 
then
	notify-send 'mplayer:' "Pressione 's' para salvar o estado atual da webcam como imagem. " ; mplayer -title "mplayer_webcam" tv:// -tv driver=v4l2:width=320:height=240:device=/dev/video0 -fps 60 -vf screenshot
elif [ "$ask" = "640x480" ] 
then
	notify-send 'mplayer:' "Pressione 's' para salvar o estado atual da webcam como imagem. " ; mplayer -title "mplayer_webcam" tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0 -fps 60 -vf screenshot
fi

