#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"

[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | dam \
  -f "Berkeley Nerd Font:size=16:Pixelsize" \
  -sf "$color00" \
  -sb "$color08" \
  -nf "$color05" \
  -nb "$color00"
