[shell]
name = "zshell"
path = "zsh"

[template.licenses]
headers = true
default = [
  "MIT",
]

[template.plugins.default]
tests = true

[template.plugins.default]
ci = true

[template.plugins.default]
src-layout = true
