#!/bin/sh

feh --bg-fill ~/pictures/wall/comfy.jpg &
xrdb merge ~/public/xresources/nord/.xresources &

picom & 

cp -r ~/public/theme\ and\ icons/flux/.gtkrc-2.0 ~/ &
cp -r ~/public/theme\ and\ icons/flux/settings.ini  ~/.config/gtk-3.0/ &

cp -r ~/public/rofi/dwm_nord/rofi/ ~/.config/ &

xbacklight -set 10 &
~/.dwm/bar &

xmodmap ~/.xmodmap-sid &
dwm
