encryption = "gpg"
[gpg]
  recipient = "706FB8A9B34E2DB2ED6085F933E88F03C18688E3"
[merge]
  command = "nvim"
  args = ["-d", "{{ .Destination  }}", "{{ .Source  }}", "{{ .Target  }}"]

[diff]
  command = "nvim"
  args = ["-d", "{{ .Destination }}", "{{ .Target }}"]
