#!/bin/env python

import os

# DMENU_ARGS=str(subprocess.run(['bash' , '/home/pablo951_br/Downloads/scripts/dmenu_args'],stdout=subprocess.PIPE).stdout.decode('utf-8').rstrip())

#DMENU_ARGS = str(os.popen('/home/pablo951_br/Downloads/scripts/dmenu_args').read().rstrip())
DMENU_ARGS = ""

def tty_termite_and(x):
    os.system("notify-send -i '%s' '<b>android , tty e termite</b>' 'Aplicando o tema'"%(x))
    os.system("/home/pablo951_br/Downloads/scripts/wall_cores_android '%s'"%(x))
    os.system("notify-send -i '%s' '<b>android , tty e termite</b>' 'Senha de Root para refazer a <b>initramfs</b> e afins'"%(x))
    os.system('/home/pablo951_br/Downloads/scripts/cores_tty_termite_gui.sh')
    os.system("notify-send -i '%s' '<b>android , tty e termite</b>' 'tema aplicado'"%(x))

def image():
    os.system("notify-send -t 10000 '<b>Modifier = Ctrl+x</b>' 'Aperter <b>m</b> para marcar a imagem desejada e <b>q</b> para continuar'") 
    path0 = str(os.popen('find /home/pablo951_br/.imagens -type d | dmenu -l 3 %s -p Diretorio:'%(DMENU_ARGS)).read().rstrip())
    path = str(os.popen("find '%s' | sxiv -tiof" %(path0)).read().rstrip())
    print(path)
    return path

def wallpaper(x):
    path = x
    os.system("nitrogen --head=0 --set-scaled '%s' ; nitrogen --head=1 --set-scaled '%s' && notify-send -i '%s' 'Wallpaper changed.'" %(path,path,path))
    os.system("printf '[xin_0]\nfile='%s'\nmode=0\nbgcolor=#222222\n\n[xin_1]\nfile='%s'\nmode=0\nbgcolor=#222222' > /home/pablo951_br/.config/nitrogen/bg-saved.cfg "%(path,path))

def backend():
    os.system("notify-send '<b>Backend:</b>' 'Escolha o backend do pywal'")
    backend=str(os.popen(("printf 'wal\nschemer2\ncolorthief\nhaishoku\ncolorz' | dmenu -i %s -p 'Backend: '" %(DMENU_ARGS))).read().rstrip())
    return backend

def interativo():
    path = image()
    back = backend()
    os.system("wal -n -i '%s' --backend %s"%(path,back))
    os.system("notify-send -i '%s' 'Colorscheme changed.'" %(path))
    os.system("echo '[wallaper]\n'%s'\n\n[tema]\nwal -i '%s' --backend %s' > ~/Downloads/Outros/ultimo-tema-wal.txt" %(path,path,backend)) 
    wall = str(os.popen("notify-send '<b>Wallpaper</b>' 'Deseja mudar o wallpaper?' ; printf 'no\nyes' | dmenu -i %s -p 'Wallpaper'" %(DMENU_ARGS)).read().rstrip())
    if(wall=='yes'):
        wallpaper(path)
    andro = str(os.popen("notify-send '<b>android , tty e termite</b>' 'Deseja mudar o tema?*\n\n<i>obs:o android deverá estar com o adb(wifi ou cabo) ativado</i>' ; printf 'no\nyes' | dmenu -i %s -p 'Android'" %(DMENU_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(path)


def clip():
    clip = str(os.popen('xclip -o -selection clipboard').read().rstrip())
    print(clip)
    back = backend()
    os.system("wal -n -i '%s' --backend %s" %(clip,back))
    wall = str(os.popen("notify-send '<b>Wallpaper</b>' 'Deseja mudar o wallpaper?' ; printf 'no\nyes' | dmenu -i %s -p 'Wallpaper'" %(DMENU_ARGS)).read().rstrip())
    if(wall=='yes'):
        wallpaper(clip)
    andro = str(os.popen("notify-send '<b>android , tty e termite</b>' 'Deseja mudar o tema?*\n\n<i>obs:o android deverá estar com o adb(wifi ou cabo) ativado</i>' ; printf 'no\nyes' | dmenu -i %s -p 'Android'" %(DMENU_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(clip)


def tema():
    os.system("notify-send -t 10000 '<b>Tema:</b>' 'Escolha um tema pré-definido pelo pywal*\n\n<i>Os melhores temas estão no arquivo ~/Downloads/Outros/pywall-best-themes.txt</i>'")
    tema = str(os.popen("cat /home/pablo951_br/Downloads/Outros/pywall-best-themes.txt | dmenu -l 3 %s -p Tema:" %(DMENU_ARGS)).read().rstrip())
    os.system('wal --theme %s'%(tema))
    os.system("notify-send '<b>Tema:</b>' 'Tema: <b>%s</b> aplicado!'" %(tema))
    os.system("echo 'wal --theme %s' > ~/Downloads/Outros/ultimo-tema-wal.txt" %(tema)) 
    wall = str(os.popen("notify-send '<b>Wallpaper</b>' 'Deseja mudar o wallpaper?' ; printf 'no\nyes' | dmenu -i %s -p 'Wallpaper'" %(DMENU_ARGS)).read().rstrip())
    if(wall=='yes'):
        wallp = image()
        wallpaper(wallp) 
    andro = str(os.popen("notify-send '<b>android , tty e termite</b>' 'Deseja mudar o tema?*\n\n<i>obs:o android deverá estar com o adb(wifi ou cabo) ativado</i>' ; printf 'no\nyes' | dmenu -i %s -p 'Android'" %(DMENU_ARGS)).read().rstrip())
    if(andro=='yes'):
        tty_termite_and(wallp)
        

#***COMEÇO***

os.system("notify-send <b>chcolor</b>: 'Script para setar as cores do pywal no sistema, termite e tty'")

#pergunta se será :  imagem modo interativo(sxiv) , imagem via clipboard ou tema pre-feito do pywwal
os.system("notify-send -t 10000 '<b>MODUS-OPERANDI:</b>' '\n<b>Interativo:</b> Abre uma janela do sxiv onde a imagem será selecionada visualmente\n\n<b>Clipboard:</b> A imagem será selecionada da clipboard\n\n<b>Tema:</b> Seerá selecionado um tema pré-feito do pywal*\n\n<i>*temas preferidos no arquivo Downloads/Outros/pywall-best-themes.txt</i>'") 

while(True):
    ask0 =  str(os.popen("printf 'interativo\nclipboard\ntema' | dmenu %s -p 'Modo:'" %(DMENU_ARGS)).read().rstrip())

    if (ask0 == 'tema'):
        tema()
        break
    elif (ask0 == 'clipboard'):
        clip()
        break
    elif (ask0 == 'interativo'):
        interativo()
        break
    else:
        quit()

