#!/usr/bin/python

#script para criar um pacote mágico e então manda-lo para um endereço

import os

def main():
    
    print()
    network=str(input("Em qual rede o PC se encontra? \n\n1=LAN\n2=WAN\n\n>>> "))
    print()
    
    #if(True):host=''
    if(network=='1'):host=''
    elif(network=='2'):host='-h pablo951br.sytes.net -p 60956'
    else:
        print("Escolha incorreta!")
        print()
        main()
    
    os.system('wol ec:a8:6b:b8:30:1f %s' %(host))
main()

