#!/bin/bash

/home/pablo951_br/Downloads/scripts/get_pywal_colors.sh && cat /home/pablo951_br/cores.txt | tail -n +2 > /home/pablo951_br/colors.properties
# adb connect 192.168.0.101:5555 &> /dev/null
adb push /home/pablo951_br/colors.properties /sdcard/Download/colors.properties && rm ~/cores.txt ~/colors.properties
adb push "$1" /sdcard/Download/wallpaper

adb shell am start -n com.termux/com.termux.app.TermuxActivity
adb shell input text '/data/data/com.termux/files/home/scripts/pc_pywal'
adb shell input keyevent 66

