#!/bin/sh

DIALOG_RESULT=$(echo -e 'exit dwm\nsuspend\nreboot\nshutdown' | dmenu -i -p "power options" -l 5)

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "exit dwm" ];
then
    killall Xorg
elif [ "$DIALOG_RESULT" = "suspend" ];
then
    exec systemctl suspend
    # systemctl suspend
elif [ "$DIALOG_RESULT" = "reboot" ];
then
    # exec reboot
    reboot
elif [ "$DIALOG_RESULT" = "shutdown" ];
then
    # exec shutdown -h now
    shutdown -h now
fi
