#!/usr/bin/python

import os

def main():

    #<head>
    print()
    network=str(input("Em qual rede o PC se encontra? \n\n1=LAN\n2=WAN\n\n>>> "))
    print()
    #<head/>

    if(network=='1'):host='192.168.1.101'
    elif(network=='2'):host='pablo951br.sytes.net'
    else:
        print("Escolha incorreta")
        main()

    os.system("ssh %s -l pablo951_br -p 60951 'sudo systemctl suspend'" %(host))

main()
