#!/usr/bin/env bash

declare -A BROWSER_FLAGS=(
    ["surf"]="-F"
    ["firefox"]="--new-tab"
    ["chromium"]="--new-tab"
    ["dmenu"]="-p html_preview -l 3"
)

for i in ${!BROWSER_FLAGS[*]}; do
    BROWSERS+="${i}\n"
done && BROWSERS=${BROWSERS%%"dmenu\n"}

ASK="$(printf "$BROWSERS" | dmenu ${BROWSER_FLAGS[dmenu]})"
$ASK ${BROWSER_FLAGS[$ASK]} "$1" &>/dev/null &
