#!/usr/bin/python


import os

def main():
    
    print()
    network=str(input("Em qual rede o PC se encontra? \n\n1=LAN\n2=WAN\n\n>>> "))
    print()
    
    #if(True):host=''
    if(network=='1'):host='192.168.1.101'
    elif(network=='2'):host='pablo951br.sytes.net'
    else:
        print("Escolha incorreta!")
        print()
        main()
    
    os.system('ssh -L 60952:localhost:60952 -L 60953:localhost:60953 %s -l pablo951_br -p 60951' %(host))

main()

