#!/bin/sh

source ~/.cache/wal/colors.sh

#DMENU_ARGS="-nf #ffffff -nb #222222 -sb $color1 -sf $color15 -fn envypn-9"
DMENU_ARGS=""

day="  Daylight(6500K)"
night=" Nightlight(3600K)"  

ask=$(printf "$day\n$night" | dmenu $DMENU_ARGS -i -p "Change Display Temperature: ")
 
if [ "$ask" = "$day" ] 
then
	redshift -r -P -O 6500 &> /dev/null
elif [ "$ask" = "$night" ] 
then
	redshift -r -P -O 3600 &> /dev/null

fi
