#!/usr/bin/env python

import subprocess
import os

#retorna a clipboard por meio do xclip
def url():
    link = str(subprocess.run(['xsel','-o', '-b'] ,stdout=subprocess.PIPE).stdout.decode('utf-8').rstrip())
    return link

#baixa o audio da clipboard usando o youtube-dl
def download_audio(link):
    os.system("youtube-dl --prefer-ffmpeg --ignore-config --geo-bypass --extract-audio --audio-format aac --audio-quality 0 -o '/home/pablo951_br/%(title)s.%(ext)s' " + "'" + link + "'")

#baixa o video da clipboard usando o youtube-dl         
def download_video(link):
    os.system("youtube-dl --prefer-ffmpeg --ignore-config --geo-bypass -o '/home/pablo951_br/%(title)s.%(ext)s' " + "'" + link + "'")

print()
ask = str(input("Script para baixar vídeos/áudio usando o youtube-dl\n\n1)Áudio\n2)Vídeo\n\n>>> "))
print()

if(ask=='1'):download_audio(url())
elif(ask=='2'):download_video(url())
else:quit()

