#!/usr/bin/env python

#essa merda usa o xclip para extrair o link do video da clipboarb


from pytube import YouTube
import os
import pytube

def url():
    os.system('rm -rf /home/pablo951_br/pytube 2> /dev/null')
    os.system('mkdir /home/pablo951_br/pytube ; mkdir /home/pablo951_br/pytube/tmp')
    os.system('xclip -o > /home/pablo951_br/pytube/tmp/url')

def download():
    link_file2 = open('/home/pablo951_br/pytube/tmp/url')
    link_str = str(link_file2.read().rstrip())
    os.system("cd /home/pablo951_br/pytube/ ; pytube --itag 140 '%s'" %(link_str))
    
def convert():
    link_file = open('/home/pablo951_br/pytube/tmp/url')
    yt = YouTube(link_file.read())
    title = yt.title.rstrip()
    title = pytube.helpers.safe_filename(title)
    os.system('ffmpeg -i /home/pablo951_br/pytube/*.mp4 -vn -c:a copy "/home/pablo951_br/%s.aac"' %(title))
    print(title)
    os.system('rm -rf /home/pablo951_br/pytube')


url() 
download()
convert()

