#!/bin/sh

DIALOG_RESULT=$(echo -e 'lock\nexit dwm\nsuspend\nreboot\nshutdown' | dmenu -i -p "power options" -l 5)

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "exit dwm" ];
then
    killall Xorg
elif [ "$DIALOG_RESULT" = "suspend" ];
then
    exec systemctl suspend
    # systemctl suspend
elif [ "$DIALOG_RESULT" = "lock" ];
then
    exec lock_n_off.sh
    # systemctl suspend
elif [ "$DIALOG_RESULT" = "suspend" ];
then
    exec systemctl suspend
    # systemctl suspend
elif [ "$DIALOG_RESULT" = "reboot" ];
then
    # exec reboot
    exec systemctl reboot
elif [ "$DIALOG_RESULT" = "shutdown" ];
then
    # exec shutdown -h now
    exec systemctl poweroff
fi
