#! /bin/sh

# shellcheck disable=2046
caller="$(ps -o comm= -p $(ps -o ppid= -p $$))"
prompt="${1:-[$caller]}"

#promptfg=black promptbg=red hidden=white
#appearance="-nf #2E3436 -nb #2E3436 -sb #1793D1 -sf #f3f4f5"
appearance="-nf #2E3436 -nb #2E3436 -sb #ff3232 -sf #f3f4f5"
#font="Liberation Sans-20:Bold"
#font="monospace-10"
font="envypn-9"

dmenu -p "$prompt" -fn "$font" \
  $appearance <&-

