#!/usr/bin/bash

PREVIEW_FILE="/tmp/vim-md-preview.pdf"
INPUT_FILE=${1}
INPUT_FORMAT=${2:-"markdown"}

if [ ! -f "${1}" ]; then
    echo "[!] file ${1} not found"
    exit 2
fi

echo "[+] Vigiando arquivo"
# entr -s "pandoc -f gfm -t pdf --pdf-engine=xelatex -V linkcolor:blue -V geometry:a4paper -V geometry:margin=2cm -V mainfont='DejaVu Sans' -V monofont='DejaVu Sans Mono' -o ${PREVIEW_FILE} ${INPUT_FILE}" <<<"${INPUT_FILE}"
entr -s "pandoc -f ${INPUT_FORMAT} -t pdf --pdf-engine=pdflatex -o ${PREVIEW_FILE} ${INPUT_FILE}" <<<"${INPUT_FILE}"
