#!/usr/bin/env python

import os

def main():

    print()
    stat=input("Deseja desligar ou ligar o monitor do seu PC?\n\n1=on\n2=off\n\n>>> ")
    print()
    ntwrk=input("Em qual rede o PC se encontra? \n\n1=LAN\n2=WAN\n\n>>> ")
    
    if(ntwrk=='1'):adress='192.168.1.101'
    elif(ntwrk=='2'):adress='pablo951br.sytes.net'
    if(stat=='1'):switch='on'
    elif(stat=='2'):switch='off'
    else:
        print("Escolha incorreta")
        main()
        
    os.system("ssh %s -l pablo951_br -p 60951 'sh ~/Downloads/scripts/desligar_monitor.sh %s'" %(adress,switch))

main()
