#!/usr/bin/env bash
# export passwords to external file

shopt -s nullglob globstar
prefix=${PASSWORD_STORE_DIR:-$HOME/.password-store}
outfile=${1:-exported_passes}

for file in "$prefix"/**/*.gpg; do
    echo $file
    #file="${file/$prefix/}"
    #printf "%s\n" "Name: ${file%.*}" >> $outfile
    #pass "${file%.*}" >> $outfile
    echo "Name: ${file%$prefix/}" >> "$outfile"
    gpg2 --decrypt "${file}" >> "$outfile"
    printf "\n\n" >> $outfile
done


