#!/bin/sh
## Base16 darkbox
# Author: Pablo Alessandro Santos Hugen

BEMENU_OPTS="-b -l 10 -w -n --fn 'Berkeley Nerd Font 12' --tb #fb4934 --tf #000000 --fb #fb4934 --ff #000000 --cb #fb4934 --cf #000000 --nb #fb4934 --nf #000000 --hb #fb4934 --hf #98971a --fbb #fb4934 --fbf #98971a --ab #fb4934 --af #d5c4a1" pinentry-bemenu "$*"
