# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"

error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #50FA7B)"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"

[cmd_duration]
style = "bold #f1fa8c"

[aws]
symbol = "  "
style = "bold #ffb86c"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
style = "bold #50fa7b"
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
style = "bold #ff79c6"
symbol = " "

[git_status]
style = "bold #ff5555"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
