--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1e1f26"
foreground="#FFFFFF"
cursor="#FFFFFF"

-- Colors
color0="#1e1f26"
color1="#FF5555"
color2="#50FA7B"
color3="#F1FA8C"
color4="#BD93F9"
color5="#FF79C6"
color6="#8BE9FD"
color7="#F8F8F2"
color8="#6272A4"
color9="#FF6E6E"
color10="#69FF94"
color11="#FFFFA5"
color12="#D6ACFF"
color13="#FF92DF"
color14="#A4FFFF"
color15="#FFFFFF"
