--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#000000"
foreground="#ffffff"
cursor="#ffffff"

-- Colors
color0="#000000"
color1="#ff004d"
color2="#00e756"
color3="#fff024"
color4="#83769c"
color5="#ff77a8"
color6="#29adff"
color7="#ffffff"
color8="#008751"
color9="#ff004d"
color10="#00e756"
color11="#fff024"
color12="#83769c"
color13="#ff77a8"
color14="#29adff"
color15="#fff1e8"
