# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1e1f26'
foreground='#FFFFFF'
cursor='#FFFFFF'

# Colors
color0='#1e1f26'
color1='#FF5555'
color2='#50FA7B'
color3='#F1FA8C'
color4='#BD93F9'
color5='#FF79C6'
color6='#8BE9FD'
color7='#F8F8F2'
color8='#6272A4'
color9='#FF6E6E'
color10='#69FF94'
color11='#FFFFA5'
color12='#D6ACFF'
color13='#FF92DF'
color14='#A4FFFF'
color15='#FFFFFF'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
