#!/data/data/com.termux/files/usr/bin/bash
TITLE=${1:-"input"}
HINT=${2:-"text"}
JSON_OUT="$(termux-dialog text -t "$TITLE" -i "$HINT")"
TEXT_OUT=$(jq .text <<<"$JSON_OUT")
echo $TEXT_OUT | tr -d '"'
